### ISSUE TITLE
UTF8 error: invalid utf-8 sequence of 1 bytes from index 0

### ISSUE THREAD

**Issue by kaihavice** [iovxw/rssbot#105]
我在bot里面订阅这个rss地址，http://voice.hupu.com/generated/voice/news_soccer.xml 报错 订阅失败: 解析错误（UTF8 error: invalid utf-8 sequence of 1 bytes from index 0）服务器环境 centos7

**Comment by iovxw** [comment]
升级时忘记启用非 UTF8 编码支持了，下个 release 就是修好的了
