### ISSUE TITLE
编译报错，可以帮助解决吗？

### ISSUE THREAD

**Issue by zrj766** [iovxw/rssbot#11]
使用的是最新版nightly，系统是centos7
`[root@zrj766 ~]# cd rssbot-1.4.2
[root@zrj766 rssbot-1.4.2]# cargo build --release
  
 Compiling regex v0.2.10

error: linker `cc` not found
  |
  
= note: No such file or directory (os error 2)

error: aborting due to previous error

error: Could not compile `regex`.

To learn more, run the command again with --verbose.

[root@zrj766 rssbot-1.4.2]#`

**Comment by iovxw** [comment]
安装 gcc
