### ISSUE TITLE
推送的消息体，能否只显示文章标题而隐藏RSS源名称

### ISSUE THREAD

**Issue by isbzx** [iovxw/rssbot#114]
**背景**：尝试用这个工具推送微博单一用户RSS的新消息

**目的**：请教能否设置修改推送tg消息的组成，想要隐去每条消息开头的RSS源名称

**原因**：因为只订阅一个RSS源的情况，每次tg推送通知也都会显示RSS源名称，有些冗余；
个人对代码修改不熟悉，部署说明中没有找到相关可配置项

附图示例 参考
感谢帮助

![jpg](https://i.loli.net/2020/08/10/2YvUa6oSd4KM3V1.png)
![jpg](https://i.loli.net/2020/08/10/HEydBl4sL7b91WJ.png)

**Comment by iovxw** [comment]
暂不支持，添加的话需要作为运行时选项引入，现在只支持单条命令交互，不方便

可以手动修改 https://github.com/iovxw/rssbot/blob/2.x/src/fetcher.rs#L96

将

```rust
format_large_msg(format!("<b>{}</b>", Escape(&feed.title)), &items, |item| {
```

改为

```rust
format_large_msg(String::new(), &items, |item| {
```

以后的版本重新设计交互逻辑的话可能会支持

**Comment by isbzx** [comment]
自行编译 有效 感谢指导！
