### ISSUE TITLE
是否可以设置独立更新间隔？

### ISSUE THREAD

**Issue by Mit2g** [iovxw/rssbot#117]
某些订阅消息过于频繁 想要单独订阅某订阅时间间隔
看到配置文件中有 `down_time`参数 尝试修改为数字提示integer错误 应该是字符串吗？又或者并不是此用途的参数？那有相关参数可以调整吗？

**Comment by iovxw** [comment]
不支持单独设置，会优先使用 RSS 自己标注的间隔，如果没有标注则使用 `--min-interval`

原因参见：https://github.com/iovxw/rssbot/issues/114#issuecomment-672774913, 没有想好怎么交互

**Comment by Mit2g** [comment]
> 不支持单独设置，会优先使用 RSS 自己标注的间隔，如果没有标注则使用 `--min-interval`
> 
> 原因参见：[#114 (comment)](https://github.com/iovxw/rssbot/issues/114#issuecomment-672774913), 没有想好怎么交互

个人认为设置一个config.json来保存rss相关信息 例如
```
RSS地址
预设显示样式
心跳
```
将现在database中那些过往rss数据信息剥离出来 设置类似于cache的文件存储他们 在迁移过备份时也可以忽略cache仅保留config

**Comment by iovxw** [comment]
不是技术上的问题，是 telegram 现有交互方式都不够便利，如果提供过多可定制项，管理订阅很麻烦

说实话有复杂需求的话不推荐使用 telegram 这种平台订阅 RSS，这个 bot 设计本身也只是为了给群组提供即时的消息提醒，即时性和操作简单更重要

**Comment by Mit2g** [comment]
> 不是技术上的问题，是 telegram 现有交互方式都不够便利，如果提供过多可定制项，管理订阅很麻烦
> 
> 说实话有复杂需求的话不推荐使用 telegram 这种平台订阅 RSS，这个 bot 设计本身也只是为了给群组提供即时的消息提醒，即时性和操作简单更重要

目前的交互方式挺不错的 更多细节设置还是放在配置文件中比较好 如果真的需要在机器人交互 可以考虑使用[button](https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating) 而不是command 我认为这样的方式更方便个性化定制同时也可以有更多设置选项
使用Telegram订阅突出一个方便 我的使用场景是为个人订阅 这样不需要另外的rss阅读器而且配合tg的fcm推送也不额外占用资源

**Comment by iovxw** [comment]
比如这种？

![image](https://user-images.githubusercontent.com/6631572/92690716-0db5de00-f374-11ea-90d1-242c7d32c805.png)

但在目前框架下实现多层级的按钮菜单不现实，需要大量精力

年内我大概没有时间做这些，这也是为什么 2.0 的 alpha 版本都发了 9 个了也还没正式版甚至是 beta

并且允许对单个订阅进行自定义也会引入其他需求，比如是否允许全文推送，或者开启 instant view

以及当订阅数量过百时，如何选取要操作的目标也是个问题（再引入分类和搜索功能？）

而这些都不符合 bot 的设计初衷，就是简单的消息提醒。所以我个人没有动力去实现这些复杂的需求，但假如有人愿意实现，也欢迎发起 PR，我会合并的

-------------------------------

BTW：还有其他优秀的 RSS Bot 实现，比如 [flowerss-bot](https://github.com/indes/flowerss-bot)，是支持独立订阅时间设置的

**Comment by Mit2g** [comment]
> 比如这种？
> 
> ![image](https://user-images.githubusercontent.com/6631572/92690716-0db5de00-f374-11ea-90d1-242c7d32c805.png)
> 
> 但在目前框架下实现多层级的按钮菜单不现实，需要大量精力
> 
> 年内我大概没有时间做这些，这也是为什么 2.0 的 alpha 版本都发了 9 个了也还没正式版甚至是 beta
> 
> 并且允许对单个订阅进行自定义也会引入其他需求，比如是否允许全文推送，或者开启 instant view
> 
> 以及当订阅数量过百时，如何选取要操作的目标也是个问题（再引入分类和搜索功能？）
> 
> 而这些都不符合 bot 的设计初衷，就是简单的消息提醒。所以我个人没有动力去实现这些复杂的需求，但假如有人愿意实现，也欢迎发起 PR，我会合并的
> 
> BTW：还有其他优秀的 RSS Bot 实现，比如 [flowerss-bot](https://github.com/indes/flowerss-bot)，是支持独立订阅时间设置的

大致是这样的 可以将这个作为二级选项之一 也可以顺便实现以前提到其他issue的需求
当时选择rssbot就是看中搭建简单 像你提到的flowerss功能大部分都用不到 且搭建相对困难
开发还是兴趣和精力第一 不强求功能 如果有最好了！
