### ISSUE TITLE
编译到最后几步报错

### ISSUE THREAD

**Issue by ccinoo** [iovxw/rssbot#12]
Compiling tokio-core v0.1.16
   Compiling tokio-curl v0.1.11
   Compiling telebot v0.1.1 (file:///root/rssbot/telebot)
   Compiling rssbot v1.4.2 (file:///root/rssbot)
error[E0658]: `impl Trait` in return position is experimental (see issue #34511)
   --> src/feed.rs:292:6
    |
292 | ) -> Result<(Vec<u8>, String, u32)> {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable

error[E0658]: `impl Trait` in return position is experimental (see issue #34511)
   --> src/feed.rs:345:6
    |
345 | ) -> impl Future<Item = RSS, Error = Error> + 'a {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable

error[E0658]: `impl Trait` in return position is experimental (see issue #34511)
  --> src/utlis.rs:78:6
   |
78 | ) -> impl Future<Item = (), Error = telebot::Error> + 'a {
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable

error[E0658]: `impl Trait` in return position is experimental (see issue #34511)
   --> src/cmdhandles.rs:443:6
    |
443 | ) -> impl Future<Item = Option<i64>, Error = telebot::Error> + 'a {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable

error[E0658]: `impl Trait` in return position is experimental (see issue #34511)
  --> src/fetcher.rs:86:6
   |
86 | ) -> Result<(), ()> {
   |      ^^^^^^^^^^^^^^
   |
   = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `rssbot`.

To learn more, run the command again with --verbose.

**Comment by ccinoo** [comment]
升级rust后，能完成编译，但是遇到这个报错不知使用是否有问题。
warning: this feature has been stable since 1.26.0. Attribute no longer needed
 --> telebot/src/lib.rs:1:12
  |
1 | #![feature(conservative_impl_trait)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(stable_features)] on by default

   Compiling rssbot v1.4.2 (file:///home/rssbot)

**Comment by iovxw** [comment]
没问题，是我忘了去掉，不影响

**Comment by ccinoo** [comment]
好的，非常感谢。请问是否有增加些其他功能的计划？

**Comment by iovxw** [comment]
@ccinoo 暂时没有想要添加的
