### ISSUE TITLE
开启单用户模式，group中无法查看订阅列表

### ISSUE THREAD

**Issue by mpc2008cn** [iovxw/rssbot#124]
如--single-user A，试了A在bot窗口可以调用/rss返回列表，但是A在group中调用/rss或者/sub等命令无任何返回，group中只有A跟bot两个，且bot无admin权限.

**Comment by iovxw** [comment]
修好了 https://github.com/iovxw/rssbot/releases/tag/v2.0.0-alpha.9

**Comment by mpc2008cn** [comment]
> 修好了 https://github.com/iovxw/rssbot/releases/tag/v2.0.0-alpha.9

可以了👍
