### ISSUE TITLE
机器人失效

### ISSUE THREAD

**Issue by nageshuizeii** [iovxw/rssbot#14]
![image](https://user-images.githubusercontent.com/16527235/38985844-18b0cb36-43fd-11e8-8188-b96c62d0734f.png)

![image](https://user-images.githubusercontent.com/16527235/38985745-d7236822-43fc-11e8-9ef3-45172ca618a3.png)
如图，当退出vps后机器人停止工作，只有重新ssh到vps重新输入命令才能恢复，但是一旦停止就重复这个现象。

**Comment by iovxw** [comment]
https://www.ibm.com/developerworks/cn/linux/l-cn-nohup/
