### ISSUE TITLE
Bot重复发送相同内容

### ISSUE THREAD

**Issue by KevinZonda** [iovxw/rssbot#145]
![Screenshot_20201026-154626_Telegram.jpg](https://user-images.githubusercontent.com/33132228/97194889-9365df80-17a2-11eb-8fbb-5aca73a3fbf2.jpg)
![Screenshot_20201026-154615_Telegram.jpg](https://user-images.githubusercontent.com/33132228/97194893-952fa300-17a2-11eb-899d-15fc74cf12dc.jpg)

如图所示，消息延迟且重复发生。怀疑是缓存问题？

**Comment by iovxw** [comment]
不好意思，昨天迁移服务器忘了关旧机器了
