### ISSUE TITLE
同一订阅会推送两次

### ISSUE THREAD

**Issue by nageshuizeii** [iovxw/rssbot#16]
![image](https://user-images.githubusercontent.com/16527235/39615873-0551763a-4fab-11e8-868e-28f4b06890f9.png)
使用/rss确认没有重复订阅，但是会推送两次

**Comment by nageshuizeii** [comment]
是自己搭建的
其他订阅会出现，频率高。特点是刚搭建这个机器人的时候最早添加的订阅出现这种情况，新订阅没有这种情况。

**Comment by iovxw** [comment]
刚搭建是用的哪个版本？可以试试把重复的退订后重新订阅

有没有修改过推送频率？

**Comment by nageshuizeii** [comment]
最新的版本，试了退订重新订阅，还是会出现
[DATAFILE.zip](https://github.com/iovxw/rssbot/files/1976399/DATAFILE.zip)

**Comment by iovxw** [comment]
还是无法复现, 你确定没有同时开两个 rssbot 吗? 其中一个运行着旧的订阅

**Comment by nageshuizeii** [comment]
只开了一个rssbot，我清空后重新装了，到现在没有出现这个问题。可能是我这边的问题。谢谢🙏
