### ISSUE TITLE
rssbot与huginn冲突问题

### ISSUE THREAD

**Issue by nageshuizeii** [iovxw/rssbot#17]
rssbot与huginn搭建在同一个vps上，rssbot不能推送或者订阅huginn抓取生成的rss。
如下图
![image](https://user-images.githubusercontent.com/16527235/39996885-9535f0f4-57b3-11e8-8916-0b9127b10c1e.png)
域名会直接变成localhost:3000，显示在已订阅列表后无法操作，也无法退订

**Comment by iovxw** [comment]
退订直接拿显示的 URL 退就行

如果访问没问题，应该是不影响推送的

这里的域名是 huginn 自己标识的，它自己标识了一个无法访问的地址的话，最好去对应项目提交 issue

**Comment by nageshuizeii** [comment]
将huginn的链接通过google feedburner烧录后解决了！谢谢
