### ISSUE TITLE
"error trying to connect: peer misbehaved: received unadvertised sig scheme RSA_PKCS1_SHA1"

### ISSUE THREAD

**Issue by dansoftware** [iovxw/rssbot#185]
```
# /usr/local/bin/rssbot -V
rssbot 2.0.0-alpha.9

```
Cannot subscribe to an RSS: `Subscription failed (Network error （error sending request for url (https://orel.sledcom.ru/news/rss_verify/): error trying to connect: peer misbehaved: received unadvertised sig scheme RSA_PKCS1_SHA1）)`

https://orel.sledcom.ru/news/rss_verify/ is opened in a web browser for example in Chrome without any problem.

**Comment by iovxw** [comment]
SHA1 has been deprecated, for more information: https://github.com/briansmith/webpki/issues/110
