### ISSUE TITLE
开发图片版本

### ISSUE THREAD

**Issue by tomyangsh** [iovxw/rssbot#192]
能否新建一个branch，将发送的消息类型改为`<item><description>`中的图片（`<img src="...">`），并且注释文字保留原链接化的item.title？
（我想改但改不来。。。）

**Comment by faustliang** [comment]
作者大大，请问能否支持将订阅信息自动导入频道呢？

**Comment by tomyangsh** [comment]
> 作者大大，请问能否支持将订阅信息自动导入频道呢？

哎哎哎，别回复我，新开一个issue....

**Comment by iovxw** [comment]
暂时没有时间，如果有谁想实现的话：

因为使用的是特化的 RSS parser，所以先要修改 `feed.rs` 增加图片信息，然后在 `fetcher::fetch_and_push_updates` 修改消息格式就行了
