### ISSUE TITLE
特殊的RSS返回值

### ISSUE THREAD

**Issue by ererermao** [iovxw/rssbot#20]
rss: http://news.stockstar.com/rss/xml.aspx?file=xml/stock/3833.xml
返回值：http://redirect.aspx/?url=http%3A%2F%2Fstock.stockstar.com%2FSS2018060100001110.shtml

这个rss比较特殊，返回的值不是实际的url（实际url部分为:`http://stock.stockstar.com/SS2018060100001110.shtml`)，能否截取一下？

**Comment by iovxw** [comment]
`<link><![CDATA[redirect.aspx?url=http%3A%2F%2Fstock.stockstar.com%2Flist%2Flive.htm]]></link>`

这是 RSS 自身问题，它标注自己为此地址

等下个版本可能的话，我会关闭自动使用标注的地址，此类问题太多了

**Comment by ererermao** [comment]
好的，谢谢
