### ISSUE TITLE
/rss 订阅列表一直为空呢？

### ISSUE THREAD

**Issue by 5536086** [iovxw/rssbot#211]
有成功的订阅，但是/rss 订阅列表一直为空呢？

是哪里没设置好吗？

**Comment by iovxw** [comment]
是自己搭建的吗？`rssbot.json` 是否为空？

**Comment by 5536086** [comment]
> 是自己搭建的吗？`rssbot.json` 是否为空？

对呢，自己搭建的，json文件能看到订阅记录，就是bot发送/rss命令看不见，我json文件不是默认的rssbot.json。是不是受这个影响？

**Comment by iovxw** [comment]
> 我json文件不是默认的rssbot.json。是不是受这个影响？

不会

> 就是bot发送/rss命令看不见

是给频道订阅的？文件内的 `subscribers` 的值是你的 ID 吗

**Comment by 5536086** [comment]
给频道订阅的，subscribers值不少我的ID，是频道的ID

**Comment by iovxw** [comment]
那和给频道订阅时一样, 要在命令后跟上频道 id, `/rss @id`

**Comment by 5536086** [comment]
> 那和给频道订阅时一样, 要在命令后跟上频道 id, `/rss @id`
好了，谢谢大佬
