### ISSUE TITLE
请问如何设定监控的时间间隔？

### ISSUE THREAD

**Issue by WYEEE** [iovxw/rssbot#215]
作者你好，Bot非常好用

我是通过这样在Debian安装的

wget https://github.com/iovxw/rssbot/releases/download/v2.0.0-alpha.9/rssbot-zh-amd64-linux
chmod +x ./rssbot-zh-amd64-linux
nohup ./rssbot-zh-amd64-linux 422236727:AAEYbmEvLYGajn4-lYnmV_HgmAgJLCxCE4w &

请问我应该去哪里修改interval，小白一枚，烦请见谅。
请问我应该去哪里修改interval，小白一枚，烦请见谅。

**Comment by iovxw** [comment]
一般不需要设置，会自动使用 RSS 源的推荐值

要修改的话有两个参数，`--min-interval` 和 `--max-interval`，分别限制最大和最小间隔。直接加在命令里就行了，单位为秒

比如 `nohup ./rssbot-zh-amd64-linux 422236727:AAEYbmEvLYGajn4-lYnmV_HgmAgJLCxCE4w --min-interval 60 &`

就是修改最小间隔为一分钟
