### ISSUE TITLE
机器人初始化失败

### ISSUE THREAD

**Issue by yanshibin** [iovxw/rssbot#22]
thread 'main' panicked at 'failed to initialize bot: Telegram(404, "Not Found", None)', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
是因为我的IP被telegram墙了？

**Comment by moonheart** [comment]
请问下这个是怎么解决的

**Comment by oceanlvr** [comment]
出现了同样的问题

**Comment by Carrie999** [comment]
+1
