### ISSUE TITLE
Bug: 解析问题

### ISSUE THREAD

**Issue by Konano** [iovxw/rssbot#230]
![image](https://user-images.githubusercontent.com/22500116/131360115-868a7de4-d8cd-4dc2-aa0a-ec3ea7690a00.png)

有关 ' 这个符号的解析好像出现了点问题

**Comment by iovxw** [comment]
无法复现

是自己部署的吗？使用的哪个版本？请提供一下 RSS 地址

**Comment by Konano** [comment]
http://rss.nano.ac/ncm/artist/204083
http://rss.nano.ac/ncm/artist/860959
这两个 RSS 地址会稳定触发。
版本号：Release v2.0.0-alpha.10

**Comment by iovxw** [comment]
看起来是上游的变动, 暂时先降级了, 等解决后会发新 release
