### ISSUE TITLE
有无可能实现多工操作加快每次获取和推送feed的速度

### ISSUE THREAD

**Issue by ruleroller** [iovxw/rssbot#236]
可参考[这个项目](https://github.com/ayrat555/el_monitorro)的 **SYNC_WORKERS_NUMBER** 和 **DELIVER_WORKERS_NUMBER** 参数。

**Comment by iovxw** [comment]
是在什么环境下觉得速度慢？订阅量有多少？

rssbot 目前没有对拉取 RSS 的并发数量做出限制，订阅多少并发就有多少（当然有一个限制器让请求均匀分布，但这不会影响吞吐），所以不需要 SYNC_WORKERS_NUMBER

消息推送也没有限制，只是 Telegram API 本身有每秒钟请求数量限制，rssbot 设计是顶着这个上限来的，也不需要 DELIVER_WORKERS_NUMBER

**Comment by ruleroller** [comment]
我一个bot约订阅了近百个feed吧，设置的2分钟的抓取时间，因为不了解rssbot的具体的运作机制，主观以为是一个feed抓取成功了再去抓取下一个的那种很传统的模式。

抱歉，打搅啦。
