### ISSUE TITLE
“使用GET方式请求”添加什么参数？

### ISSUE THREAD

**Issue by WYEEE** [iovxw/rssbot#239]
作者大大，订阅 https://navi.cnki.net/knavi/rss/XXYY 类型的RSS，bot提示：订阅失败: 网络错误（error sending request for url (https://navi.cnki.net/knavi/rss/XXYY): error trying to connect: received fatal alert: HandshakeFailure）

是否切换GET的请求方式能解决？
求告知~~

**Comment by iovxw** [comment]
navi.cnki.net 使用了[过时的密码套件](https://www.ssllabs.com/ssltest/analyze.html?d=navi.cnki.net)，所以链接被认为不安全，rssbot 拒绝连接

有几个解决办法：

1. 直接忽略安全问题，使用 --insecure 参数，详见 README.md
1. rssbot 现在使用的 rustls 对于安全问题比较激进，可以换到 openssl 重新编译。需要的话我有空新加一个 release
1. 联系 navi.cnki.net 的管理员，让他们升级 TLS

**Comment by WYEEE** [comment]
老大，有空加一个release吧。
不知道为啥，我加 --insecure 也不生效。
😂

nohup ./rssbot-zh-amd64-linux 42XXXXX27:AAEYbmXXXXXXXXXLCxCE4w --insecure &

/sub https://navi.cnki.net/knavi/rss/XXYY

订阅失败: 网络错误（error sending request for url (https://navi.cnki.net/knavi/rss/XXYY): error trying to connect: received fatal alert: HandshakeFailure）

**Comment by iovxw** [comment]
已添加

**Comment by WYEEE** [comment]
太好使了哥，节省一大笔经费~~~~~
