### ISSUE TITLE
不支持带端口的网址吗？

### ISSUE THREAD

**Issue by menhood** [iovxw/rssbot#24]
DDNS架设的wordpress站，原生的feed，但是是用的900的端口，提示我拉取出错，打开链接发现是不带端口的地址😳

**Comment by iovxw** [comment]
检查一下 RSS 里面是不是自己标注的不带端口的网址 `<link rel="self" href="xxxxxxxx">`

于 2018年6月7日 GMT+08:00 下午6:46:08, menhood <notifications@github.com> 写到:

DDNS架设的wordpress站，原生的feed，但是是用的900的端口，提示我拉取出错，打开链接发现是不带端口的地址😳

**Comment by menhood** [comment]
搞定了 感谢
