### ISSUE TITLE
【建议】请问是否能支持单独设置每个feed的抓取时间，以秒为单位。

### ISSUE THREAD

**Issue by ruleroller** [iovxw/rssbot#262]
作者你好，😃 

请问，有无可能对每个feed设定单独的抓取频率呢，比如，在添加feed时，附上一个参数来进行控制；如果不带参数，就默认一个频率，当然，这个默认频率也希望能随时进行改动的。

这样的话，只需要一个bot就可以进行更好的控制了，不太频繁更新的feed就不那么频繁抓取，频繁更新的抓取时间设置得短一些。

**Comment by iovxw** [comment]
参见 #117

**Comment by ruleroller** [comment]
OK，看过117啦，了解了！顺其自然，一切随缘吧。
