### ISSUE TITLE
后台运行问题

### ISSUE THREAD

**Issue by nageshuizeii** [iovxw/rssbot#27]
nohup后台运行23天后，无法使用/rss /sub等命令，但是机器人在持续运行，能够正常推送，只能杀掉进程后重新运行。
![image](https://user-images.githubusercontent.com/16527235/41988943-4642e7ec-7a70-11e8-9794-7fc6f4541bd3.png)

**Comment by iovxw** [comment]
没有其他信息的话不好定位问题，公共的机器人已经连续运行三个月，没有出现过类似问题，请试试能不能稳定复现

于 2018年6月28日 GMT+08:00 上午1:12:28, nageshuizeii <notifications@github.com> 写到:

nohup后台运行23天后，无法使用/rss /sub等命令，但是机器人在持续运行，能够正常推送，只能杀掉进程后重新运行。
[image]<https://user-images.githubusercontent.com/16527235/41988943-4642e7ec-7a70-11e8-9794-7fc6f4541bd3.png>

**Comment by nageshuizeii** [comment]
作者也是才看完德国翻车无心睡觉么，好的，我试试看能不能复现，谢谢🙏
