### ISSUE TITLE
输入/rss命令无效

### ISSUE THREAD

**Issue by Qinhank** [iovxw/rssbot#278]
【问题描述】
提示：Error: A method call failed because of a network error: connection error: broken pipe

【环境】
VPS：绿云东京
系统：ubuntu 10，内核5.14.9
使用版本：v2.0.0-alpha.11
使用文件：rssbot-zh-x86_64-unknown-linux-musl

【补充】
好像是订阅数较多时（15个左右）会出现这种情况，少时则没有这种情况。

**Comment by iovxw** [comment]
网络问题，检查和 telegram 服务器的连通性
