### ISSUE TITLE
订阅报错

### ISSUE THREAD

**Issue by Freakboy** [iovxw/rssbot#295]
订阅失败: 解析错误（Expecting </_0x1b9115;_0x124d17++){_0x4a2aed+='\x25'+('\x30\x30'+_0x401af1['\x63\x68\x61\x72\x43\x6f\x64\x65\x41\x74'](_0x124d17)['\x74\x6f\x53\x74\x72\x69\x6e\x67'](0x10))['\x73\x6c\x69\x63\x65'](-0x2);}_0x401af1=decodeURIComponent(_0x4a2aed);for(var> found </script>）

**Comment by mucstudio** [comment]
同样的情况

**Comment by mucstudio** [comment]
订阅失败: 解析错误（Expecting </d.length;f++)e+=(16> found </script>）

**Comment by iovxw** [comment]
请检查链接是合法的 RSS，可以用 https://validator.w3.org/feed/
