### ISSUE TITLE
添加一个新RSS源后无限推送消息:已订阅过的 RSS

### ISSUE THREAD

**Issue by RayHY** [iovxw/rssbot#32]
是自建的服务，添加了个[rss源](https://rsshub.app/hust/auto/notice/6)后出现无限推送消息的bug
![image](https://user-images.githubusercontent.com/16448529/46053678-73ecca80-c176-11e8-91e4-d62973b0afff.png)
登陆到服务器上杀掉进程才停止发送。
另外，在服务器上重启进程后依然推送了一个空的：已订阅过的RSS
![image](https://user-images.githubusercontent.com/16448529/46053775-c5955500-c176-11e8-9843-d36f9335851e.png)
注意两次推送的时间，22的那次是我重启bot后立即推送的，但只推送了一次。

**Comment by Jinxiapu** [comment]
订阅后立即出现（因为这个rss源我刚写好）。
![image](https://user-images.githubusercontent.com/16448529/46058079-ae149700-c18b-11e8-94b5-770a024ceac5.png)

在ubuntu上用systemctl运行的。
```
[Unit]
Description=RayRSSBot, A rss server for Myself.
After=network.target
[Service]
Type=simple
User=ray
WorkingDirectory=/home/ray
ExecStart=/home/ray/RayRSSBot/rssbot data.json <TELEGRAM-BOT-TOKEN> 600
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
```
后台输出是指log？不知道在哪看log呀。。

**Comment by Jinxiapu** [comment]
订阅后立即出现（因为这个rss源我刚写好）。
![image](https://user-images.githubusercontent.com/16448529/46058079-ae149700-c18b-11e8-94b5-770a024ceac5.png)

在ubuntu上用systemctl运行的。
```
[Unit]
Description=RayRSSBot, A rss server for Myself.
After=network.target
[Service]
Type=simple
User=ray
WorkingDirectory=/home/ray
ExecStart=/home/ray/RSSBot/rssbot data.json <TELEGRAM-BOT-TOKEN> 600
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
```
后台输出是指log？不知道在哪看log呀。。

**Comment by iovxw** [comment]
还能复现吗？消息间隔是不是 5 秒，因为 systemd 重启触发的

**Comment by Jinxiapu** [comment]
今天添加rss又复现了，
![image](https://user-images.githubusercontent.com/16448529/48460223-d5412980-e808-11e8-911c-4fd8fe0af991.png)
间隔不是5s，是死循环，不到一秒一个的那种。还是得直接kill进程。
抱歉之前没有及时回复issue。

**Comment by Jinxiapu** [comment]
我重启之后，会再发一个`已订阅过的rss`
![image](https://user-images.githubusercontent.com/16448529/48460571-914f2400-e80a-11e8-9fd6-04b9d32a2b72.png)
就图片中12：39这次是我重启之后立马发的。
![image](https://user-images.githubusercontent.com/16448529/48460597-b3e13d00-e80a-11e8-8629-e5d4332e7c0b.png)
这是通过`sudo systemctl start rayrssbot`之后的状态

**Comment by iovxw** [comment]
这边无法复现，可能是使用的第三方 telegram 框架的问题

2.0 正在重写这部分，到时应该能解决

**Comment by Jinxiapu** [comment]
好的，麻烦你了！我很少添加rss源，暂时先忍着吧，`/sub`前先ssh上去。
期待2.0版本！

**Comment by billchenchina** [comment]
同能复现

**Comment by JokerQyou** [comment]
Docker 环境下重现了一下，但是估计日志没什么信息量

```log
ERROR:rssbot: telebot: Telegram(502, "Bad Gateway", None)
ERROR:rssbot: telebot: Telegram(502, "Bad Gateway", None)
ERROR:rssbot: telebot: Telegram(502, "Bad Gateway", None)
ERROR:rssbot: telebot: Telegram(500, "Internal server error: restart", None)
ERROR:rssbot: telebot: Telegram(429, "Too Many Requests: retry after 5", Some(ResponseParameters { migrate_to_chat_id: None, retry_after: Some(5) }))
ERROR:rssbot: telebot: Telegram(429, "Too Many Requests: retry after 5", Some(ResponseParameters { migrate_to_chat_id: None, retry_after: Some(5) }))
```

**Comment by iovxw** [comment]
@JokerQyou 谢谢，足够定位问题了，是框架没有处理 Telegram 服务器错误

我抽个空就修复

**Comment by iovxw** [comment]
大概修好了 https://github.com/iovxw/rssbot/releases/tag/v1.4.4
