### ISSUE TITLE
部分链接处理异常

### ISSUE THREAD

**Issue by NeverBehave** [iovxw/rssbot#4]
链接形如 
http://rss.uptimerobot.com/u474138-660612c9cd9bcb35bb3e5a396e337aa8
在`/sub`时是可以获得链接正确的内容
但是返回的信息（储存）的链接内容是错误的
http://rss.uptimerobot.com/u1-5b5168eb2ed3396e02b6b7d4459cf634/
![image](https://user-images.githubusercontent.com/17120571/34637140-2b51d7ee-f2ea-11e7-8749-7a672d35ebf5.png)

**Comment by iovxw** [comment]
<atom10:link xmlns:atom10="http://www.w3.org/2005/Atom" rel="self" type="application/rss+xml" href="http://rss.uptimerobot.com/u1-5b5168eb2ed3396e02b6b7d4459cf634/"/>

这个 feed 标注自己的地址就是这样的，实际订阅成功的地址在订阅成功的消息中有。

实际订阅地址不同会造成用户混乱，这个等找到合适的解决方案时会改进

**Comment by NeverBehave** [comment]
但是这个实际订阅地址是返回404的……导致实际上机器人获取不到信息
滚去问一下uptimerobot，这个返回有毒
