### ISSUE TITLE
Support subscribe with keyword.

### ISSUE THREAD

**Issue by fernvenue** [iovxw/rssbot#422]
Sometimes we don’t actually want all information in a feed.

For example, I subscribed [Releases - Apple Developer](https://developer.apple.com/news/releases/rss/releases.rss) on my bot just because I wanna be notified if there is any release with iOS, but now I will be notified every time when there is any releases with iOS, iPadOS, tvOS and so on…

Same thing happened with [Cloudflare Status](https://www.cloudflarestatus.com/history.atom) and [Hetzner Status](https://status.hetzner.com/en.atom), I just wanna know something related to my services, not all kinds stuff on those platforms.

Maybe subscribe with keyword will be a good idea? Is there any chance to add this kind of feature? Thanks.

**Comment by iovxw** [comment]
Try https://rssfilter.netlify.app/ or https://siftrss.com/

**Comment by fernvenue** [comment]
@iovxw Hi! Thanks for your reply, those services look good, it will be even better if rssbot can support it natively, so that we don't need to use 3rd party service or configure an additional service.
