### ISSUE TITLE
[功能请求] 支持 Pushover 转发

### ISSUE THREAD

**Issue by imjoeyli** [iovxw/rssbot#446]
不知道能否添加对 Pushover 的支持，将 RSS 条目设置转发到 Pushover 的功能，主要有几点好处：

- Pushover 可以设置更多通知优先级，例如紧急推送：Priority 1 是高优先级，可以突破 iOS 的勿扰模式
- Pushover 的消息可以存在设备本地（无限数量），作为消息备份
- Pushover 更加专注于通知，消息不会混在 Telegram 一堆聊天信息中

Pushover API 文档（主要通过 HTTP Post 实现）：https://pushover.net/api

**Comment by iovxw** [comment]
本项目是一个 telegram 机器人，要支持 Pushover 不是添加一个功能而是切换整个平台，这不在项目目标范围内
