### ISSUE TITLE
無法正常訂閱及退訂

### ISSUE THREAD

**Issue by karakarasuuuu** [iovxw/rssbot#47]
訂閱網址：https://ithelp.ithome.com.tw/rss/series/2767
在訂閱列表顯示的標題是正確的，但連結點進去會連到該文章作者的個人頁面
![image](https://user-images.githubusercontent.com/19412420/67315433-27bab800-f539-11e9-821c-6feadacee02a.png)
且無法正常退訂，圖片如下
![image](https://user-images.githubusercontent.com/19412420/67315343-f510bf80-f538-11e9-92ca-7f70b2a00316.png)

**Comment by karakarasuuuu** [comment]
Update:
![image](https://user-images.githubusercontent.com/19412420/67639140-2cabad00-f927-11e9-8c88-5f243a71b2e0.png)
使用點擊該連結所得到的網址進行退訂可正常運作

**Comment by iovxw** [comment]
参见 #4

**Comment by iovxw** [comment]
已在 2.0.0-alpha 版本中修复
