### ISSUE TITLE
Support output in English

### ISSUE THREAD

**Issue by hashworks** [iovxw/rssbot#48]
It would be nice if the bot could support English output (an English README file would be useful as well).

**Comment by jinzhengyang** [comment]
English README you can try this https://github.com/nanqinlang-mogic/RustRssBot/blob/31.March/readme.md 
they are similar but modified

**Comment by hashworks** [comment]
Regarding:
> The command description in Telegram can't be internationalized

Wouldn't a CLI flag solve this? `--lang=en`, `-l=en`.

**Comment by iovxw** [comment]
Oh, I am overthinking it.

> Wouldn't a CLI flag solve this? `--lang=en`, `-l=en`.

You're right.
