### ISSUE TITLE
运行 ./rssbot DATAFILE TELEGRAM-BOT-TOKEN 时出错了

### ISSUE THREAD

**Issue by Allen47** [iovxw/rssbot#50]
运行 ./rssbot DATAFILE TELEGRAM-BOT-TOKEN 时出错了

![image](https://user-images.githubusercontent.com/45147571/73603088-d64eaa00-45b8-11ea-925f-1837233cde31.png)

**Comment by iovxw** [comment]
确保你的服务器可以访问 Telegram
