### ISSUE TITLE
无法订阅某些rss(含atom)

### ISSUE THREAD

**Issue by 70akaline** [iovxw/rssbot#51]
https://www.nature.com/subjects/physics/ncomms.atom
https://www.nature.com/subjects/physics/ncomms.rss

这两个feed都没办法订阅，提示，订阅失败: HTTP 303 (See Other)

**Comment by iovxw** [comment]
暂不支持 303 跳转。2.0 版本正在写，会支持的

**Comment by iovxw** [comment]
alpha 版本写好了，可以先用 https://github.com/iovxw/rssbot/releases/tag/v2.0.0-alpha
