### ISSUE TITLE
关于 2.0 alpha版本 无法顺利启动的问题

### ISSUE THREAD

**Issue by Zephylaci** [iovxw/rssbot#57]
我先运行了 1.44 的编译后版本
确认key，网络环境正确无误，并可以工作
再运行了 2.0 alpha 然无法顺利启动
如图：
![GjgB6I.png](https://s1.ax1x.com/2020/04/13/GjgB6I.png)

代理配置是类似：
export http_proxy=$proxy
export https_proxy=$proxy
export no_proxy="localhost, 127.0.0.1, ::1"

我想知道，我还缺什么？

**Comment by iovxw** [comment]
程序不支持从环境变量读取代理，用其他方式挂代理吧

**Comment by Zephylaci** [comment]
@iovxw 
我又倒腾了一番....试了下用 proxychains 直接拉起程序
或者用proxychains拉个bash再去拉起程序
用这两个方法，我都能正常访问谷歌..
但对2.0版的程序，似乎无效..依旧是上面的提示..
我想请教下，2.0版的程序支持哪种挂代理的方式？

**Comment by iovxw** [comment]
Release 里提供的是静态链接版本，proxychains 不支持静态链接的程序，可以手动编译一个动态的版本（默认方式编译就是）

主要是动态链接分发比较麻烦，所以没提供。我有时间实现一下读取代理的环境变量吧

**Comment by iovxw** [comment]
[2.0.0-alpha.2](https://github.com/iovxw/rssbot/releases/tag/v2.0.0-alpha.2) 已支持读取代理
