### ISSUE TITLE
订阅不推送

### ISSUE THREAD

**Issue by Butanediol** [iovxw/rssbot#63]
Bangumi 时间胶囊生成的 RSS 订阅不推送，但其他的没问题。
[时间胶囊](https://bgm.tv/feed/user/butanediol/timeline)
手机或电脑上的 RSS 客户端可以正常订阅，服务器也可以正常读取订阅，但在 Telegram 中不推送。

希望能帮忙看一下是什么问题，感谢。

**Comment by iovxw** [comment]
什么版本？2.0 的话会遵守 RSS 内设置的 ttl 时间

这个 RSS 的 ttl 为 720 也就是  12 小时，所以 12 小时推送一次

如果觉得太长，机器人有个命令行参数 `--max-interval`  可以限制最大 ttl，单位为秒

**Comment by Butanediol** [comment]
谢谢，原来是这样。
