### ISSUE TITLE
无法订阅uptimerobot

### ISSUE THREAD

**Issue by lanbu88** [iovxw/rssbot#8]
我本人订阅的链接是http://rss.uptimerobot.com/u2299xx-xxxxxxxxxxxxxxxxxxxxxxx
但/rss查看的时候却是另一个链接
http://rss.uptimerobot.com/u1-5b5168eb2ed3396e02b6b7d4459cf634/

**Comment by iovxw** [comment]
这站有问题，他里面描述的就是这个链接 `<atom10:link xmlns:atom10="http://www.w3.org/2005/Atom" rel="self" type="application/rss+xml" href="http://rss.uptimerobot.com/u1-5b5168eb2ed3396e02b6b7d4459cf634/"/>`
