### ISSUE TITLE
订阅失败：RSS 超出大小限制（2MiB）

### ISSUE THREAD

**Issue by wym3253** [iovxw/rssbot#81]
https://share.dmhy.org/topics/rss/rss.xml?keyword=&sort_id=0&team_id=657&order=date-desc
在订阅上方链接时无法成功订阅，请问有什么方法可以解除大小限制吗

**Comment by huihuimoe** [comment]
如果是selfhost的rssbot的话，临时的解决方法是更改这个常量重新编译即可

https://github.com/iovxw/rssbot/blob//d0144ade59ef080fe5df7b5e584c6498ed4bdcb2/src/client.rs#L13

**Comment by iovxw** [comment]
我有空加一个命令行参数控制这个吧
