### ISSUE TITLE
支持权限控制

### ISSUE THREAD

**Issue by hsupu** [iovxw/rssbot#87]
可否增加限制，是否允许用户操作 bot？白名单机制？

**Comment by iovxw** [comment]
有想过实现单用户模式（只有一个名额的白名单），但还不确定需求就没写

如果要实现的话你希望以怎样的方式进行控制？

**Comment by hsupu** [comment]
我想，单用户模式已经可以满足大多数自建 rssbot 之需求。

查过 tgbot API，提供了 id username 两个途径标识用户，那么：

- 以 username 控制是容易而有效的办法。
- 第一个 username 需要在命令行里传入，或是谁先发起 /admin 命令谁就是。
- 也许可以通过某种方式在日志里打出 id，然后以 id 来控制。

你怎么看？

**Comment by iovxw** [comment]
Telegram 不允许 bot 直接用 username 查找用户，靠发消息的话不太干净，我加一个说明推荐用 [@userinfobot](https://t.me/userinfobot)  [@getidsbot](https://t.me/getidsbot) 之类的获取自己的 id 吧

这两天抽空就实现下
