### ISSUE TITLE
[feature] may not be used on the stable release channe

### ISSUE THREAD

**Issue by ccinoo** [iovxw/rssbot#9]
#cargo build --release
   Compiling proc-macro2 v0.1.4
$<2>error[E0554]$<2>$<2>: #![feature] may not be used on the stable release channel$<2>
  $<2>$<2>--> $<2>/root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.1.4/src/lib.rs:22:35$<2>
   $<2>$<2>|$<2>
$<2>22$<2> $<2>$<2>| $<2>#![cfg_attr(feature = "unstable", feature(proc_macro))]$<2>
   $<2>$<2>| $<2>                                  $<2>$<2>^^^^^^^^^^^^^^^^^^^^$<2>

$<2>error$<2>$<2>: aborting due to previous error$<2>

error: Could not compile `proc-macro2`.

To learn more, run the command again with --verbose

**Comment by ccinoo** [comment]
Compiling proc-macro2 v0.1.3
     Running `rustc --crate-name proc_macro2 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.1.3/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="unstable"' -C metadata=a35ea6711ad5263a -C extra-filename=-a35ea6711ad5263a --out-dir /root/rssbot-1.4.1/target/debug/deps -L dependency=/root/rssbot-1.4.1/target/debug/deps --extern unicode_xid=/root/rssbot-1.4.1/target/debug/deps/libunicode_xid-5ab8279c3be8661d.rlib --cap-lints allow`
error[E0277]: the trait bound `proc_macro::Span: std::default::Default` is not satisfied
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.1.3/src/unstable.rs:163:17
    |
163 | pub struct Span(proc_macro::Span);
    |                 ^^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `proc_macro::Span`
    |
    = note: required by `std::default::Default::default`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `proc-macro2`.

**Comment by iovxw** [comment]
`cargo +nightly build --release`

**Comment by ccinoo** [comment]
Thank you very much, the problem has been solved.
