### ISSUE TITLE
程序反应非常慢甚至无反应

### ISSUE THREAD

**Issue by luojianxhlxt** [iovxw/rssbot#94]
![反应](https://user-images.githubusercontent.com/8614534/84230864-801de480-ab1f-11ea-915d-1aba9a176a5f.JPG)

这是北京时间13.36的截图

**Comment by iovxw** [comment]
自己搭建的？检查一下服务器网络吧

**Comment by luojianxhlxt** [comment]
> 自己搭建的？检查一下服务器网络吧

电报就是连的这个服务器，看油管之类的也没有问题哦。还是要怎样测试网络呢

**Comment by iovxw** [comment]
使用的是哪个版本？可以 ping 一下 api.telegram.org，bot 和 telegram 客户端可能使用的不是同一个 telegram 服务器

**Comment by luojianxhlxt** [comment]
> 使用的是哪个版本？可以 ping 一下 api.telegram.org，bot 和 telegram 客户端可能使用的不是同一个 telegram 服务器

目前跑的是v2.0.0-alpha.7。
我的服务器是在外网

> root@GIA:~# ping api.telegram.org
PING api.telegram.org (149.154.167.220) 56(84) bytes of data.
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=1 ttl=45 time=140 ms
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=2 ttl=45 time=140 ms
64 bytes from 149.154.167.220 (149.154.167.220): icmp_seq=3 ttl=45 time=148 ms
^C
--- api.telegram.org ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 4ms
rtt min/avg/max/mdev = 139.733/142.529/147.927/3.817 ms

**Comment by iovxw** [comment]
没有头绪，重启 bot 有效吗？

可以的话请提供一下 rssbot.json，我的邮箱是 iovxw@outlook.com

**Comment by luojianxhlxt** [comment]
> 没有头绪，重启 bot 有效吗？
> 
> 可以的话请提供一下 rssbot.json，我的邮箱是 [iovxw@outlook.com](mailto:iovxw@outlook.com)

重启无效，稍等下我发给你

**Comment by iovxw** [comment]
> 重启无效，稍等下我发给你

收到

试了一下无法复现，看内容也很正常

应该就是你服务器环境内有什么影响了

可以检查一下有没有设置 HTTPS_PROXY 之类的环境变量，或者 bot 的 token 被多个 bot 共用这样的

还不行就只能联系你的服务器提供商排查问题了

**Comment by luojianxhlxt** [comment]
> > 重启无效，稍等下我发给你
> 
> 收到
> 
> 试了一下无法复现，看内容也很正常
> 
> 应该就是你服务器环境内有什么影响了
> 
> 可以检查一下有没有设置 HTTPS_PROXY 之类的环境变量，或者 bot 的 token 被多个 bot 共用这样的
> 
> 还不行就只能联系你的服务器提供商排查问题了

可是我使用1.4.4版本的就很正常哦
![1 4 4](https://user-images.githubusercontent.com/8614534/84243473-d47f8f00-ab34-11ea-8668-741fe90b06fc.JPG)

**Comment by iovxw** [comment]
用其他服务器也有这个现象吗？

我这边确实无法复现，也就定位不了问题

2.x 版本是完全重写的，靠现有信息也无法排查

**Comment by iovxw** [comment]
请逐条尝试以下方法：

- 直接从命令行启动，不使用 service manager（例如 systemd，pm2）
- `unset HTTPS_PROXY` 再运行
- 禁用 IPv6
- 使用新的 bot token

再不行就换个服务器试试吧，这类问题需要排查的范围过大，一般就是环境配置影响，很难定位

**Comment by Newlearner365** [comment]
遇到同样的问题，之前一直在用 1.x 版本，直到某网站订阅显示网络错误，在月初更新到了 2.0.

**Comment by Newlearner365** [comment]
命令行启动，

> 遇到同样的问题，之前一直在用 1.x 版本，直到某网站订阅显示网络错误，在月初更新到了 2.0.

命令行启动，没有设置代理，没有 ipv6，更换了服务器也比较卡顿。

**Comment by iovxw** [comment]
@Newlearner365 试一下这个版本: [rssbot.zip](https://github.com/iovxw/rssbot/files/4814085/rssbot.zip)，修改了 DNS 的实现，之前发给 @luojianxhlxt 测试说有效果

很有可能是服务器没有 IPv6 但 bot 却使用了 IPv6，fallback 到  IPv4 时出现了一点问题

**Comment by Newlearner365** [comment]
> rssbot.zip

用了您提供的版本，目前一切正常，非常感谢您的帮助！

**Comment by iovxw** [comment]
虽然修复了不过我本地一直没有复现成功

@Newlearner365 能提供一下出问题时 bot 的命令行输出、服务器所使用的 DNS (`/etc/resolv.conf`)以及服务器提供商的信息吗？

我向上游反馈一下

**Comment by Newlearner365** [comment]
> 虽然修复了不过我本地一直没有复现成功
> 
> @Newlearner365 能提供一下出问题时 bot 的命令行输出、服务器所使用的 DNS (`/etc/resolv.conf`)以及服务器提供商的信息吗？
> 
> 我向上游反馈一下

我整理放在这里：https://paste.ubuntu.com/p/8NrVh6hv8b/
